#!/usr/bin/env python3
from ex04 import ALLOWED_CHARACTERS, print_truth_table
import sys


if __name__ == "__main__":
    if len(sys.argv) != 2 or not set(s := sys.argv[1]) <= ALLOWED_CHARACTERS or not s:
        print("Usage:", sys.argv[0], f"'[{''.join(sorted(ALLOWED_CHARACTERS))}]+'")
        print("Example:", sys.argv[0], "'AB&C|'")
        sys.exit(1)
    try:
        print_truth_table(s)
    except (AssertionError, IndexError):
        print(s, "is malformatted")
